# Numpy

In [191]:
import numpy as np

In [192]:
lista = ["a", 1, True, 2 + 3j, ["a", "b"], {"k" : 90}]
lista

['a', 1, True, (2+3j), ['a', 'b'], {'k': 90}]

In [193]:
#np.array(lista)

In [194]:
np.array([1, 2, 3])

array([1, 2, 3])

In [195]:
np.array(["a", "b", "c"])

array(['a', 'b', 'c'], dtype='<U1')

In [196]:
np.array({True, "a"})

array({True, 'a'}, dtype=object)

In [197]:
a = np.array([[1, 2, 8], [3, 4, 6]])
a

array([[1, 2, 8],
       [3, 4, 6]])

In [198]:
a.shape

(2, 3)

In [199]:
a.size

6

In [200]:
np.zeros((3, 5, 5, 2, 9))

array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]],


        [[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]],


        [[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0.,

In [201]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [202]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [203]:
np.array(list(range(5)))

array([0, 1, 2, 3, 4])

In [204]:
np.arange(1, 25, 2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5])

In [205]:
a, da = np.linspace(0, 10, 20, retstep = True)

In [206]:
a

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [207]:
da

np.float64(0.5263157894736842)

In [208]:
np.arange(1, 5).reshape((2, 2))

array([[1, 2],
       [3, 4]])

In [209]:
a = np.linspace(1, 100, 100).reshape((25, 4))

In [210]:
a[-1, 1 :]

array([ 98.,  99., 100.])

In [211]:
np.random.normal(0, 1, 10000)

array([ 0.02045406, -0.74927596, -0.50401028, ..., -0.09015313,
        0.79604832,  0.88319936], shape=(10000,))

**Actividad** Del arreglo con distribución normal, cuenta cuantas entradas están más alejadas de tres desviaciones estándar

In [212]:
mu = 0
sigma = 1
n = 1_000_000
a = np.random.normal(mu, sigma, n)
a[np.abs(a) > 3 * sigma].size / n

0.002739

In [213]:
a = np.linspace(0, 10, 10000)
a

array([0.00000000e+00, 1.00010001e-03, 2.00020002e-03, ...,
       9.99799980e+00, 9.99899990e+00, 1.00000000e+01], shape=(10000,))

In [214]:
a + 10

array([10.       , 10.0010001, 10.0020002, ..., 19.9979998, 19.9989999,
       20.       ], shape=(10000,))

In [215]:
for i in range(a.size):
    a[i] += 10

a

array([10.       , 10.0010001, 10.0020002, ..., 19.9979998, 19.9989999,
       20.       ], shape=(10000,))

In [216]:
m = 2
b = 1
x = np.linspace(0, 10, 101)
y = m * x + b

In [217]:
x

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [218]:
y

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. ])

In [219]:
y = 3 * np.sin(x * np.pi)
y

array([ 0.00000000e+00,  9.27050983e-01,  1.76335576e+00,  2.42705098e+00,
        2.85316955e+00,  3.00000000e+00,  2.85316955e+00,  2.42705098e+00,
        1.76335576e+00,  9.27050983e-01,  3.67394040e-16, -9.27050983e-01,
       -1.76335576e+00, -2.42705098e+00, -2.85316955e+00, -3.00000000e+00,
       -2.85316955e+00, -2.42705098e+00, -1.76335576e+00, -9.27050983e-01,
       -7.34788079e-16,  9.27050983e-01,  1.76335576e+00,  2.42705098e+00,
        2.85316955e+00,  3.00000000e+00,  2.85316955e+00,  2.42705098e+00,
        1.76335576e+00,  9.27050983e-01,  1.10218212e-15, -9.27050983e-01,
       -1.76335576e+00, -2.42705098e+00, -2.85316955e+00, -3.00000000e+00,
       -2.85316955e+00, -2.42705098e+00, -1.76335576e+00, -9.27050983e-01,
       -1.46957616e-15,  9.27050983e-01,  1.76335576e+00,  2.42705098e+00,
        2.85316955e+00,  3.00000000e+00,  2.85316955e+00,  2.42705098e+00,
        1.76335576e+00,  9.27050983e-01,  1.83697020e-15, -9.27050983e-01,
       -1.76335576e+00, -

In [220]:
a = np.linspace(1, 4, 4).reshape((2, 2))
a

array([[1., 2.],
       [3., 4.]])

In [221]:
b = np.array([2, 2])
b

array([2, 2])

In [222]:
a.dot(b)

array([ 6., 14.])

In [223]:
a @ b

array([ 6., 14.])

**Actividad** Repite el ejercicio de los 30 volados, pero con arreglos de numpy

In [224]:
n = 10000
a = np.random.binomial(1, 0.5, (n, 30)).sum(axis = 1) >= 21
a.sum() / n

np.float64(0.0183)

In [225]:
(np.random.binomial(1, 0.5, (5, 10)).sum(axis = 1) >= 5).sum()

np.int64(2)

In [226]:
a = np.random.normal(0, 1, (6, 5))
a

array([[ 0.08776152,  0.0518495 ,  1.28373613, -0.01372251,  1.4522784 ],
       [-0.95022877,  0.11204862,  0.74118951,  0.26408432, -1.89849763],
       [ 0.18424243, -2.07204973, -1.90886467, -0.35980551,  0.46410875],
       [-1.3724059 ,  2.04032303,  1.75129483,  0.99814751, -0.15894449],
       [ 0.94799768, -0.50502401,  0.40795013,  0.57148109,  0.09903483],
       [ 1.45790666, -0.84044179, -1.59217972,  0.22293929, -0.8966453 ]])

In [227]:
a.sum(axis = 1)

array([ 2.86190305, -1.73140395, -3.69236873,  3.25841499,  1.52143972,
       -1.64842085])

In [228]:
a.mean(axis = 1)

array([ 0.57238061, -0.34628079, -0.73847375,  0.651683  ,  0.30428794,
       -0.32968417])

In [229]:
a.std(axis = 1)

array([0.65262117, 0.95282038, 1.05728324, 1.26582446, 0.48859287,
       1.06555966])

In [230]:
a.max(axis = 1)

array([1.4522784 , 0.74118951, 0.46410875, 2.04032303, 0.94799768,
       1.45790666])

In [231]:
a.min(axis = 1)

array([-0.01372251, -1.89849763, -2.07204973, -1.3724059 , -0.50502401,
       -1.59217972])

In [232]:
a.var(axis = 1)

array([0.42591439, 0.90786667, 1.11784785, 1.60231155, 0.23872299,
       1.13541739])

In [233]:
a

array([[ 0.08776152,  0.0518495 ,  1.28373613, -0.01372251,  1.4522784 ],
       [-0.95022877,  0.11204862,  0.74118951,  0.26408432, -1.89849763],
       [ 0.18424243, -2.07204973, -1.90886467, -0.35980551,  0.46410875],
       [-1.3724059 ,  2.04032303,  1.75129483,  0.99814751, -0.15894449],
       [ 0.94799768, -0.50502401,  0.40795013,  0.57148109,  0.09903483],
       [ 1.45790666, -0.84044179, -1.59217972,  0.22293929, -0.8966453 ]])

In [234]:
a[a >= 1]

array([1.28373613, 1.4522784 , 2.04032303, 1.75129483, 1.45790666])

In [235]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [236]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [237]:
q, r = np.linalg.qr(a)

In [238]:
q

array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]])

In [239]:
r

array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]])

In [240]:
import scipy.integrate as integrate

In [241]:
x_funcion = lambda x : 1 / x**2
integrate.quad(x_funcion, 0.1, 1)

(8.999999999999998, 2.1220320566968197e-10)

In [242]:
v = lambda x: x + 1
v

<function __main__.<lambda>(x)>

In [243]:
u = lambda x, y: x*y + 1 if x > 0 else 0
u

<function __main__.<lambda>(x, y)>

In [244]:
w = lambda x, y, i : x[i - 1] + y[i - 1]
w

<function __main__.<lambda>(x, y, i)>

In [245]:
x = np.linspace(0, 10, 11)
y = np.linspace(-10, 0, 11)
z = np.zeros(11)

for i in range(x.size):
    z[i] = w(x, y, i)

z

array([ 10., -10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.])

In [246]:
pitagorica = lambda x : np.sin(x) * np.sin(x) + np.cos(x) * np.cos(x)
pitagorica

<function __main__.<lambda>(x)>

In [247]:
pitagorica(-200)

np.float64(1.0)

In [248]:
x = np.linspace(0, 10000, 1000000)
r = pitagorica(x)
r

array([1., 1., 1., ..., 1., 1., 1.], shape=(1000000,))

In [260]:
r[0] = -1
np.all(r[r == 1.])

np.True_

In [261]:
r[r==1.]

array([1., 1., 1., ..., 1., 1., 1.], shape=(777223,))